--<ScriptOptions statementTerminator=";"/>

CREATE SCHEMA "Schema";

CREATE TABLE "Schema"."DATAMENEGER" (
		"DATAMENEGER_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		"USERPROPERTIESWINDOWUSERPROPERTIESWINDOW_ID" INTEGER NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "Schema"."EMPLOYEE" (
		"EMPLOYEE_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		"EMPLOYEEMANAGEREMPLOYEEMANAGER_ID" INTEGER NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "Schema"."EMPLOYEEMANAGER" (
		"EMPLOYEEMANAGER_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER )
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "Schema"."PROJECT" (
		"PROJECTNAME" VARCHAR(32672), 
		"PROJECT_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		"PROJECTMANAGERPROJECTMANAGER_ID" INTEGER NOT NULL, 
		"PROJECTMANAGER2PROJECTMANAGER_ID" INTEGER NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "Schema"."PROJECTMANAGER" (
		"PROJECTMANAGER_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		"WIDOKPROJEKTYWIDOKPROJEKTY_ID" INTEGER NOT NULL, 
		"WIDOKPROJEKTYWIDOKPROJEKTYWIDOKPROJEKTY_ID" INTEGER NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "Schema"."PROJECTS" (
		"PROJECTS_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER )
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "Schema"."TASK" (
		"TASKNAME" CHAR(10), 
		"TASKOWNER" CHAR(10), 
		"TASK_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		"PROJECTPROJECT_ID" INTEGER NOT NULL, 
		"TASKMANAGERTASKMANAGER_ID" INTEGER NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "Schema"."TASKMANAGER" (
		"TASKMANAGER_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		"WIDOKNOWEZADANIAWIDOKNOWEZADANIA_ID" INTEGER NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "Schema"."TIMESHEET" (
		"IDTIMESHEET" CHAR(10), 
		"TIMESHEET_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		"TIMESHEETMANAGERTIMESHEETMANAGER_ID" INTEGER NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "Schema"."TIMESHEETMANAGER" (
		"TIMESHEETMANAGER_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		"WIDOKTIMESHEETWIDOKTIMESHEET_ID" INTEGER NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "Schema"."USERDETAILSDAO" (
		"USERDETAILSDAO_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		"DATAMENEGERDATAMENEGER_ID" INTEGER NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "Schema"."USERPROPERTIESWINDOW" (
		"USERPROPERTIESWINDOW_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER )
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "Schema"."WIDOKNOWEZADANIA" (
		"WIDOKNOWEZADANIA_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER )
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "Schema"."WIDOKPROJEKTY" (
		"WIDOKPROJEKTY_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER )
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "Schema"."WIDOKTIMESHEET" (
		"WIDOKTIMESHEET_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER )
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE "Schema"."DATAMENEGER" ADD CONSTRAINT "DATAMENEGER_PK" PRIMARY KEY
	("DATAMENEGER_ID");

ALTER TABLE "Schema"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY
	("EMPLOYEE_ID");

ALTER TABLE "Schema"."EMPLOYEEMANAGER" ADD CONSTRAINT "EMPLOYEEMANAGER_PK" PRIMARY KEY
	("EMPLOYEEMANAGER_ID");

ALTER TABLE "Schema"."PROJECT" ADD CONSTRAINT "PROJECT_PK" PRIMARY KEY
	("PROJECT_ID");

ALTER TABLE "Schema"."PROJECTMANAGER" ADD CONSTRAINT "PROJECTMANAGER_PK" PRIMARY KEY
	("PROJECTMANAGER_ID");

ALTER TABLE "Schema"."PROJECTS" ADD CONSTRAINT "PROJECTS_PK" PRIMARY KEY
	("PROJECTS_ID");

ALTER TABLE "Schema"."TASK" ADD CONSTRAINT "TASK_PK" PRIMARY KEY
	("PROJECTPROJECT_ID", 
	 "TASK_ID");

ALTER TABLE "Schema"."TASKMANAGER" ADD CONSTRAINT "TASKMANAGER_PK" PRIMARY KEY
	("TASKMANAGER_ID");

ALTER TABLE "Schema"."TIMESHEET" ADD CONSTRAINT "TIMESHEET_PK" PRIMARY KEY
	("TIMESHEET_ID");

ALTER TABLE "Schema"."TIMESHEETMANAGER" ADD CONSTRAINT "TIMESHEETMANAGER_PK" PRIMARY KEY
	("TIMESHEETMANAGER_ID");

ALTER TABLE "Schema"."USERDETAILSDAO" ADD CONSTRAINT "USERDETAILSDAO_PK" PRIMARY KEY
	("USERDETAILSDAO_ID");

ALTER TABLE "Schema"."USERPROPERTIESWINDOW" ADD CONSTRAINT "USERPROPERTIESWINDOW_PK" PRIMARY KEY
	("USERPROPERTIESWINDOW_ID");

ALTER TABLE "Schema"."WIDOKNOWEZADANIA" ADD CONSTRAINT "WIDOKNOWEZADANIA_PK" PRIMARY KEY
	("WIDOKNOWEZADANIA_ID");

ALTER TABLE "Schema"."WIDOKPROJEKTY" ADD CONSTRAINT "WIDOKPROJEKTY_PK" PRIMARY KEY
	("WIDOKPROJEKTY_ID");

ALTER TABLE "Schema"."WIDOKTIMESHEET" ADD CONSTRAINT "WIDOKTIMESHEET_PK" PRIMARY KEY
	("WIDOKTIMESHEET_ID");

ALTER TABLE "Schema"."DATAMENEGER" ADD CONSTRAINT "DATAMENEGER_USERPROPERTIESWINDOW_FK" FOREIGN KEY
	("USERPROPERTIESWINDOWUSERPROPERTIESWINDOW_ID")
	REFERENCES "Schema"."USERPROPERTIESWINDOW"
	("USERPROPERTIESWINDOW_ID");

ALTER TABLE "Schema"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_EMPLOYEEMANAGER_FK" FOREIGN KEY
	("EMPLOYEEMANAGEREMPLOYEEMANAGER_ID")
	REFERENCES "Schema"."EMPLOYEEMANAGER"
	("EMPLOYEEMANAGER_ID");

ALTER TABLE "Schema"."PROJECT" ADD CONSTRAINT "PROJECT_PROJECTMANAGER_FK" FOREIGN KEY
	("PROJECTMANAGERPROJECTMANAGER_ID")
	REFERENCES "Schema"."PROJECTMANAGER"
	("PROJECTMANAGER_ID");

ALTER TABLE "Schema"."PROJECT" ADD CONSTRAINT "PROJECT_PROJECTMANAGER_FK1" FOREIGN KEY
	("PROJECTMANAGER2PROJECTMANAGER_ID")
	REFERENCES "Schema"."PROJECTMANAGER"
	("PROJECTMANAGER_ID");

ALTER TABLE "Schema"."PROJECTMANAGER" ADD CONSTRAINT "PROJECTMANAGER_WIDOKPROJEKTY_FK" FOREIGN KEY
	("WIDOKPROJEKTYWIDOKPROJEKTY_ID")
	REFERENCES "Schema"."WIDOKPROJEKTY"
	("WIDOKPROJEKTY_ID");

ALTER TABLE "Schema"."PROJECTMANAGER" ADD CONSTRAINT "PROJECTMANAGER_WIDOKPROJEKTY_FK1" FOREIGN KEY
	("WIDOKPROJEKTYWIDOKPROJEKTYWIDOKPROJEKTY_ID")
	REFERENCES "Schema"."WIDOKPROJEKTY"
	("WIDOKPROJEKTY_ID");

ALTER TABLE "Schema"."TASK" ADD CONSTRAINT "TASK_PROJECT_FK" FOREIGN KEY
	("PROJECTPROJECT_ID")
	REFERENCES "Schema"."PROJECT"
	("PROJECT_ID");

ALTER TABLE "Schema"."TASK" ADD CONSTRAINT "TASK_TASKMANAGER_FK" FOREIGN KEY
	("TASKMANAGERTASKMANAGER_ID")
	REFERENCES "Schema"."TASKMANAGER"
	("TASKMANAGER_ID");

ALTER TABLE "Schema"."TASKMANAGER" ADD CONSTRAINT "TASKMANAGER_WIDOKNOWEZADANIA_FK" FOREIGN KEY
	("WIDOKNOWEZADANIAWIDOKNOWEZADANIA_ID")
	REFERENCES "Schema"."WIDOKNOWEZADANIA"
	("WIDOKNOWEZADANIA_ID");

ALTER TABLE "Schema"."TIMESHEET" ADD CONSTRAINT "TIMESHEET_TIMESHEETMANAGER_FK" FOREIGN KEY
	("TIMESHEETMANAGERTIMESHEETMANAGER_ID")
	REFERENCES "Schema"."TIMESHEETMANAGER"
	("TIMESHEETMANAGER_ID");

ALTER TABLE "Schema"."TIMESHEETMANAGER" ADD CONSTRAINT "TIMESHEETMANAGER_WIDOKTIMESHEET_FK" FOREIGN KEY
	("WIDOKTIMESHEETWIDOKTIMESHEET_ID")
	REFERENCES "Schema"."WIDOKTIMESHEET"
	("WIDOKTIMESHEET_ID");

ALTER TABLE "Schema"."USERDETAILSDAO" ADD CONSTRAINT "USERDETAILSDAO_DATAMENEGER_FK" FOREIGN KEY
	("DATAMENEGERDATAMENEGER_ID")
	REFERENCES "Schema"."DATAMENEGER"
	("DATAMENEGER_ID");

