<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="UseCase"
    nsURI="http:///UseCase.ecore" nsPrefix="UseCase">
  <eAnnotations source="com.ibm.xtools.common.ui.reduction.editingCapabilities">
    <details key="com.ibm.xtools.activities.umlBBLifeLine" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBEvent1" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBEvent2" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBTypes2" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBSubsystem" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBStateMachine1" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBTypes4" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBActivity1" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBStateMachine2" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBSequence1" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBActivity2" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBSequence2" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBActivity3" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBDeploymentDiagram" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBFunction" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBComponent" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBAction" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBPackage" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBCollaboration" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBInstance" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBArtifact" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBComment1" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBComment2" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBCompositeStructure1" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBCompositeStructure2" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBClass" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBUsage" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBSequenceDiagram" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBRealization" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBCommunication" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBDeploymentSpecification" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBInterface" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBUseCaseDiagram" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBStateChartDiagram" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBFragment" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBClassDiagram" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBSignal" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBCommunicationDiagram" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBActivityDiagram" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBInteraction" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBInformationFlow" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBRelationship1" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBRelationship2" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBFreeFormDiagram" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBDeployment1" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBComponentDiagram" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBDeployment2" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBStructureDiagram" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBUseCase1" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBUseCase2" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBCollaborationUse" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBDependancy" value="1"/>
    <details key="com.ibm.xtools.activities.umlBBConstraint" value="1"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="WidokProjekty">
    <eOperations name="getProjectList" ordered="false" lowerBound="1"/>
    <eOperations name="selectProject" ordered="false" lowerBound="1"/>
    <eOperations name="closeProject" ordered="false" lowerBound="1"/>
    <eOperations name="DeleteEmployeeView" ordered="false" lowerBound="1"/>
    <eOperations name="SelectEmployee" ordered="false" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectManager">
    <eOperations name="getProjects" ordered="false" lowerBound="1"/>
    <eOperations name="showProjectDetails" ordered="false" lowerBound="1"/>
    <eOperations name="checkPermission" ordered="false" lowerBound="1"/>
    <eOperations name="closeProject" ordered="false" lowerBound="1"/>
    <eOperations name="ShowEmployeeList" ordered="false" lowerBound="1"/>
    <eOperations name="DeleteEmployee" ordered="false" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eOperations name="getProjectsDB" ordered="false" lowerBound="1"/>
    <eOperations name="getProjectDetailsDB" ordered="false" lowerBound="1"/>
    <eOperations name="closeProjectDB" ordered="false" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidokNoweZadania">
    <eOperations name="createNewTaskClicked" ordered="false" lowerBound="1"/>
    <eOperations name="saveTaskClicked" ordered="false" lowerBound="1"/>
    <eOperations name="showConfirmationMessage" ordered="false" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskManager">
    <eOperations name="showNewTaskForm" ordered="false" lowerBound="1"/>
    <eOperations name="saveTask" ordered="false" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task">
    <eOperations name="createNewTask" ordered="false" lowerBound="1"/>
    <eOperations name="saveTask" ordered="false" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmployeeManager">
    <eOperations name="GetEmployeeList" ordered="false" lowerBound="1"/>
    <eOperations name="RemoveEmployee" ordered="false" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserPropertiesWindow">
    <eOperations name="getEmployeeList" ordered="false" lowerBound="1"/>
    <eOperations name="getUserProperties" ordered="false" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserDetailsDAO">
    <eOperations name="getDataDB" ordered="false" lowerBound="1"/>
    <eOperations name="getUserDetailsDB" ordered="false" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataMeneger">
    <eOperations name="getUsersData" ordered="false" lowerBound="1"/>
    <eOperations name="getUserDetails" ordered="false" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserDetailsDAO"/>
  <eClassifiers xsi:type="ecore:EClass" name="WidokProjekt"/>
  <eClassifiers xsi:type="ecore:EClass" name="WidokProjekty"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectManager"/>
  <eClassifiers xsi:type="ecore:EClass" name="WidokProjekty"/>
  <eClassifiers xsi:type="ecore:EClass" name="WidokProjekty"/>
  <eClassifiers xsi:type="ecore:EClass" name="WidokProjekty">
    <eOperations name="newProjectClick" ordered="false" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectManager">
    <eOperations name="createProject" ordered="false" lowerBound="1"/>
    <eOperations name="checkPermission" ordered="false" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Project"/>
  <eClassifiers xsi:type="ecore:EClass" name="Projects">
    <eOperations name="createProjectDB" ordered="false" lowerBound="1"/>
  </eClassifiers>
  <eSubpackages name="UseCaseBuildingBlocks" nsURI="http:///UseCase/UseCaseBuildingBlocks.ecore"
      nsPrefix="UseCase.UseCaseBuildingBlocks">
    <eSubpackages name="$functionalarea" nsURI="http:///UseCase/UseCaseBuildingBlocks/$functionalarea.ecore"
        nsPrefix="UseCase.UseCaseBuildingBlocks.$functionalarea"/>
  </eSubpackages>
  <eSubpackages name="VersatileActors" nsURI="http:///UseCase/VersatileActors.ecore"
      nsPrefix="UseCase.VersatileActors"/>
  <eSubpackages name="Overviews" nsURI="http:///UseCase/Overviews.ecore" nsPrefix="UseCase.Overviews"/>
</ecore:EPackage>
